name: Packer fmt and validate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Format Packer Template
        run: |

          # Run packer fmt and capture the exit code
           packer fmt -check .

          # Check the exit code and fail the workflow if changes were made
          if [ $? -ne 0 ]; then
           echo "Packer template formatting check failed. Please run 'packer fmt' locally and commit the changes."
           exit 1
          fi

      - name: Validate Packer Template
        run: |
          # Run packer validate and capture the exit code
          packer validate -syntax-only .

          # Check the exit code and fail the workflow if validation fails
          if [ $? -ne 0 ]; then
            echo "Packer template validation failed. Please ensure the template is correct before merging the pull request."
            exit 1
          fi